### ISSUE TITLE
Setup Server Side Sdk in Typescript for next-13 and subsequently client side sdk for react.

### ISSUE THREAD

**Issue by Neon-20** [One-Click-Auth/Trustauthx_TS_SDK#2]
Setup Server Side Sdk in Typescript for next-13 and subsequently client side sdk for react.
Brownie points for vanilla js sdk.

Functions are already exposed here (server side ) : https://github.com/One-Click-Auth/Trustauthx_TS_SDK/blob/main/src/index.ts
Client side: https://github.com/One-Click-Auth/Trustauthx_TS_SDK/blob/main/src/client.ts

We are facing few issues regarding storing the tokens in cookies.
This is a paid gig.
Contact the team here for more info: https://discord.gg/qrB4Dzes

**Comment by shmbajaj** [comment]
Hey @Neon-20 I would like to contribute on this issue.

I don't have experience with SDK and Next.js,
but I am confident to enough to read docs, ask and get it done.

So, I cannot give ETA but daily updates for sure.

**Comment by sahilsuman933** [comment]
Closed this issue as the example has been implemented and moved to another repository.
